# Generated by Django 3.0.8 on 2020-07-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['user'], name='user_index'),
        ),
    ]
