# Generated by Django 3.0.8 on 2020-07-26 10:28

from django.db import migrations, models
import drafter.models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0002_auto_20200726_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='name',
            field=models.CharField(default=drafter.models.get_random_draft_name, max_length=256),
        ),
    ]
