# Generated by Django 3.1 on 2020-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0003_auto_20200726_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='entries',
            field=models.JSONField(default=list),
        ),
    ]
