# Generated by Django 3.1 on 2020-09-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0006_auto_20200913_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameweek',
            options={'ordering': ['gw_id']},
        ),
    ]
