# Generated by Django 3.1 on 2020-10-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0007_auto_20200913_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='unavailable',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
