# Generated by Django 3.1 on 2021-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0008_draft_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='cloned',
            field=models.BooleanField(default=False),
        ),
    ]
