version: "3.7"

x-services:
  draftnik: &draftnik
    hostname: draftnik
    env_file:
      - ops/.env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    restart: on-failure:5
    volumes:
      - .:/code
      - draftnik-ipython:/root/.ipython

services:
  webserver:
    <<: *draftnik
    container_name: draftnik-webserver
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  db:
    image: postgres:12-alpine
    container_name: draftnik-postgres
    environment:
      - POSTGRES_USER=draftnik
      - POSTGRES_PASSWORD=draftnik
    volumes:
      - draftnik-data-postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: draftnik-redis
    volumes:
      - draftnik-data-redis:/data

  celery:
    <<: *draftnik
    container_name: draftnik-celery
    command: celery -A draftnik worker --concurrency=20 --loglevel=info

  celery-beat:
    <<: *draftnik
    container_name: draftnik-celery-beat
    command: celery -A draftnik beat --loglevel=info

volumes:
  draftnik-ipython:
  draftnik-data-postgres:
  draftnik-data-redis:
